
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TOGGLE 2
#define VIAL_KEYBOARD_UID {0x45, 0xEE, 0xB2, 0xB2, 0xFE, 0x38, 0xF4, 0x4D}
#define VIAL_UNLOCK_COMBO_ROWS {0,9}
#define VIAL_UNLOCK_COMBO_COLS {0,5}